title: Maximilian Götz
author: Maximilian Götz
description: The homepage of Maximilian Götz
baseurl: ""
url: "https://goetz.pro"
permalink: "/:categories/:year/:month/:day/:title"
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - /bin
